baseurl: /
exclude: ['README.md']
permalink: /:title/
contact: dataanalytics@coleridgeinitiative.org
scholarship_doc: assets/docs/old.ScholarshipAppInstructions.pdf
registration_link: https://mailchi.mp/50936e0129a8/coleridge-mailing-list
