- section: Content Overview
  class: content-overview
  subsections:
    - title: ""
      paragraphs:
        - "The Coleridge Initiative's 1st training program in Applied Data Analytics for Public Policy brought together 57 participants from over 30 different local, state, and federal agencies to analyze factors contributing to recidivism."
    - title: Data and Sponsoring Agencies
      paragraphs:
        - "Three different agencies contributed data for use in the training materials..."

- section: The Projects
  class: projects
  subsections:
    - title: ""
      paragraphs:
        - "This training program was centered around projects and each participant was grouped into teams of 4-5."

- section: The Participants
  class: participants
  subsections:
    - title: ""
      paragraphs:
        - "(Participant & agency list)"
